import 'package:flutter/material.dart';
import 'package:gap/gap.dart';
import 'package:poc_web_size/pages/p75/widgets/widgets.dart';

class Page75 extends StatelessWidget {
  const Page75({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: const Padding(
          padding: EdgeInsets.only(top: 20, left: 20, right: 20),
          child: SingleChildScrollView(
            child: Column(
              children: [
                SizedBox(
                  height: 200,
                  child: Center(
                    child: Text(
                      'Page 75',
                      style: TextStyle(fontSize: 32),
                    ),
                  ),
                ),
                Row(
                  children: [
                    Widget1(),
                    Gap(10),
                    Widget2(),
                    Gap(10),
                    Widget3(),
                    Gap(10),
                    Widget4(),
                    Gap(10),
                    Widget5(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget6(),
                    Gap(10),
                    Widget7(),
                    Gap(10),
                    Widget8(),
                    Gap(10),
                    Widget9(),
                    Gap(10),
                    Widget10(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget11(),
                    Gap(10),
                    Widget12(),
                    Gap(10),
                    Widget13(),
                    Gap(10),
                    Widget14(),
                    Gap(10),
                    Widget15(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget16(),
                    Gap(10),
                    Widget17(),
                    Gap(10),
                    Widget18(),
                    Gap(10),
                    Widget19(),
                    Gap(10),
                    Widget20(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget21(),
                    Gap(10),
                    Widget22(),
                    Gap(10),
                    Widget23(),
                    Gap(10),
                    Widget24(),
                    Gap(10),
                    Widget25(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget26(),
                    Gap(10),
                    Widget27(),
                    Gap(10),
                    Widget28(),
                    Gap(10),
                    Widget29(),
                    Gap(10),
                    Widget30(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget31(),
                    Gap(10),
                    Widget32(),
                    Gap(10),
                    Widget33(),
                    Gap(10),
                    Widget34(),
                    Gap(10),
                    Widget35(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget36(),
                    Gap(10),
                    Widget37(),
                    Gap(10),
                    Widget38(),
                    Gap(10),
                    Widget39(),
                    Gap(10),
                    Widget40(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget41(),
                    Gap(10),
                    Widget42(),
                    Gap(10),
                    Widget43(),
                    Gap(10),
                    Widget44(),
                    Gap(10),
                    Widget45(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget46(),
                    Gap(10),
                    Widget47(),
                    Gap(10),
                    Widget48(),
                    Gap(10),
                    Widget49(),
                    Gap(10),
                    Widget50(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget51(),
                    Gap(10),
                    Widget52(),
                    Gap(10),
                    Widget53(),
                    Gap(10),
                    Widget54(),
                    Gap(10),
                    Widget55(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget56(),
                    Gap(10),
                    Widget57(),
                    Gap(10),
                    Widget58(),
                    Gap(10),
                    Widget59(),
                    Gap(10),
                    Widget60(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget61(),
                    Gap(10),
                    Widget62(),
                    Gap(10),
                    Widget63(),
                    Gap(10),
                    Widget64(),
                    Gap(10),
                    Widget65(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget66(),
                    Gap(10),
                    Widget67(),
                    Gap(10),
                    Widget68(),
                    Gap(10),
                    Widget69(),
                    Gap(10),
                    Widget70(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget71(),
                    Gap(10),
                    Widget72(),
                    Gap(10),
                    Widget73(),
                    Gap(10),
                    Widget74(),
                    Gap(10),
                    Widget75(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget76(),
                    Gap(10),
                    Widget77(),
                    Gap(10),
                    Widget78(),
                    Gap(10),
                    Widget79(),
                    Gap(10),
                    Widget80(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget81(),
                    Gap(10),
                    Widget82(),
                    Gap(10),
                    Widget83(),
                    Gap(10),
                    Widget84(),
                    Gap(10),
                    Widget85(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget86(),
                    Gap(10),
                    Widget87(),
                    Gap(10),
                    Widget88(),
                    Gap(10),
                    Widget89(),
                    Gap(10),
                    Widget90(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget91(),
                    Gap(10),
                    Widget92(),
                    Gap(10),
                    Widget93(),
                    Gap(10),
                    Widget94(),
                    Gap(10),
                    Widget95(),
                  ],
                ),
                Gap(20),
                Row(
                  children: [
                    Widget96(),
                    Gap(10),
                    Widget97(),
                    Gap(10),
                    Widget98(),
                    Gap(10),
                    Widget99(),
                    Gap(10),
                    Widget100(),
                  ],
                ),
                Gap(20),
              ],
            ),
          ),
        ));
  }
}
